## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    bld.program(
        source = 'ctest_alloc.c',
        target = 'ctest_alloc',
        includes = '. ../zero',
        use = 'gkylzero',
    )
