## -*- python -*-
# Build code in this directory
##    _______     ___
## + 6 @ |||| # P ||| +

import os

def build(bld):
    source = r"""
    alloc.c
    array.c
    array_ops.c
    array_rio.c
    cart_modal_serendip.c
    dg_eqn.c
    dg_vlasov.c
    gauss_quad_data.c
    hyper_dg.c
    mom_calc.c
    mom_type.c
    optparse.c
    proj_on_basis.c
    range.c
    rect_grid.c
    util.c
    vlasov_mom.c
    """

    # For now building static library. Probably should build shared
    # library as well. In fact, shared-lib is needed to allow linking
    # to interpreted language FFIs
    bld.stlib(source = source,
              includes = '. ..',
              target = 'gkylzero',
              name = 'gkylzero',
    )
